service:
  name: short-url-service
  version: v1.0.0

server:
  http:
    addr: 0.0.0.0:5000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123456@tcp(localhost:3306)/shorturl?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  mongodb:
    uri: mongodb://127.0.0.1:27017  # MongoDB连接URI
    dbname: shorturl             # 数据库名称
    timeout: 30s                    # 连接超时时间
nsq:
  lookupd_addresses: ["127.0.0.1:4161"]  # NSQ Lookupd 地址
  nsqd_address: "127.0.0.1:4150"         # NSQD 地址
  topic: "shorturl_access"                # 主题名称
  channel: "db_worker"                    # 通道名称
  concurrency: 5                          # 并发消费者数量