// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: shorturl/public/v1/shorturl.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LongUrl       string                 `protobuf:"bytes,1,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	ExpireTime    string                 `protobuf:"bytes,2,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenRequest) Reset() {
	*x = ShortenRequest{}
	mi := &file_shorturl_public_v1_shorturl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenRequest) ProtoMessage() {}

func (x *ShortenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shorturl_public_v1_shorturl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenRequest.ProtoReflect.Descriptor instead.
func (*ShortenRequest) Descriptor() ([]byte, []int) {
	return file_shorturl_public_v1_shorturl_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenRequest) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

func (x *ShortenRequest) GetExpireTime() string {
	if x != nil {
		return x.ExpireTime
	}
	return ""
}

type ShortenReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenReply) Reset() {
	*x = ShortenReply{}
	mi := &file_shorturl_public_v1_shorturl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenReply) ProtoMessage() {}

func (x *ShortenReply) ProtoReflect() protoreflect.Message {
	mi := &file_shorturl_public_v1_shorturl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenReply.ProtoReflect.Descriptor instead.
func (*ShortenReply) Descriptor() ([]byte, []int) {
	return file_shorturl_public_v1_shorturl_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenReply) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ShortenReply) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ShortenReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	LongUrl       string                 `protobuf:"bytes,3,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	CreateAt      string                 `protobuf:"bytes,4,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	ExpireTime    string                 `protobuf:"bytes,5,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_shorturl_public_v1_shorturl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_shorturl_public_v1_shorturl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_shorturl_public_v1_shorturl_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

func (x *Data) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *Data) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

func (x *Data) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

func (x *Data) GetExpireTime() string {
	if x != nil {
		return x.ExpireTime
	}
	return ""
}

var File_shorturl_public_v1_shorturl_proto protoreflect.FileDescriptor

const file_shorturl_public_v1_shorturl_proto_rawDesc = "" +
	"\n" +
	"!shorturl/public/v1/shorturl.proto\x12\vshorturl.v1\x1a\x1cgoogle/api/annotations.proto\"L\n" +
	"\x0eShortenRequest\x12\x19\n" +
	"\blong_url\x18\x01 \x01(\tR\alongUrl\x12\x1f\n" +
	"\vexpire_time\x18\x02 \x01(\tR\n" +
	"expireTime\"c\n" +
	"\fShortenReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12%\n" +
	"\x04data\x18\x02 \x01(\v2\x11.shorturl.v1.DataR\x04data\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x9b\x01\n" +
	"\x04Data\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\x12\x19\n" +
	"\blong_url\x18\x03 \x01(\tR\alongUrl\x12\x1b\n" +
	"\tcreate_at\x18\x04 \x01(\tR\bcreateAt\x12\x1f\n" +
	"\vexpire_time\x18\x05 \x01(\tR\n" +
	"expireTime2k\n" +
	"\x06Public\x12a\n" +
	"\x0eCreateShortUrl\x12\x1b.shorturl.v1.ShortenRequest\x1a\x19.shorturl.v1.ShortenReply\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/api/shortenB,Z*backend-shorturl/api/shorturl/public/v1;v1b\x06proto3"

var (
	file_shorturl_public_v1_shorturl_proto_rawDescOnce sync.Once
	file_shorturl_public_v1_shorturl_proto_rawDescData []byte
)

func file_shorturl_public_v1_shorturl_proto_rawDescGZIP() []byte {
	file_shorturl_public_v1_shorturl_proto_rawDescOnce.Do(func() {
		file_shorturl_public_v1_shorturl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shorturl_public_v1_shorturl_proto_rawDesc), len(file_shorturl_public_v1_shorturl_proto_rawDesc)))
	})
	return file_shorturl_public_v1_shorturl_proto_rawDescData
}

var file_shorturl_public_v1_shorturl_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_shorturl_public_v1_shorturl_proto_goTypes = []any{
	(*ShortenRequest)(nil), // 0: shorturl.v1.ShortenRequest
	(*ShortenReply)(nil),   // 1: shorturl.v1.ShortenReply
	(*Data)(nil),           // 2: shorturl.v1.Data
}
var file_shorturl_public_v1_shorturl_proto_depIdxs = []int32{
	2, // 0: shorturl.v1.ShortenReply.data:type_name -> shorturl.v1.Data
	0, // 1: shorturl.v1.Public.CreateShortUrl:input_type -> shorturl.v1.ShortenRequest
	1, // 2: shorturl.v1.Public.CreateShortUrl:output_type -> shorturl.v1.ShortenReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shorturl_public_v1_shorturl_proto_init() }
func file_shorturl_public_v1_shorturl_proto_init() {
	if File_shorturl_public_v1_shorturl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shorturl_public_v1_shorturl_proto_rawDesc), len(file_shorturl_public_v1_shorturl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shorturl_public_v1_shorturl_proto_goTypes,
		DependencyIndexes: file_shorturl_public_v1_shorturl_proto_depIdxs,
		MessageInfos:      file_shorturl_public_v1_shorturl_proto_msgTypes,
	}.Build()
	File_shorturl_public_v1_shorturl_proto = out.File
	file_shorturl_public_v1_shorturl_proto_goTypes = nil
	file_shorturl_public_v1_shorturl_proto_depIdxs = nil
}
