// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend-shorturl/internal/data/ent/schema"
	"backend-shorturl/internal/data/ent/shorturl"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	shorturlMixin := schema.Shorturl{}.Mixin()
	shorturlMixinFields0 := shorturlMixin[0].Fields()
	_ = shorturlMixinFields0
	shorturlFields := schema.Shorturl{}.Fields()
	_ = shorturlFields
	// shorturlDescCreateTime is the schema descriptor for create_time field.
	shorturlDescCreateTime := shorturlMixinFields0[0].Descriptor()
	// shorturl.DefaultCreateTime holds the default value on creation for the create_time field.
	shorturl.DefaultCreateTime = shorturlDescCreateTime.Default.(func() time.Time)
	// shorturlDescUpdateTime is the schema descriptor for update_time field.
	shorturlDescUpdateTime := shorturlMixinFields0[1].Descriptor()
	// shorturl.DefaultUpdateTime holds the default value on creation for the update_time field.
	shorturl.DefaultUpdateTime = shorturlDescUpdateTime.Default.(func() time.Time)
	// shorturl.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	shorturl.UpdateDefaultUpdateTime = shorturlDescUpdateTime.UpdateDefault.(func() time.Time)
	// shorturlDescShortCode is the schema descriptor for short_code field.
	shorturlDescShortCode := shorturlFields[1].Descriptor()
	// shorturl.ShortCodeValidator is a validator for the "short_code" field. It is called by the builders before save.
	shorturl.ShortCodeValidator = shorturlDescShortCode.Validators[0].(func(string) error)
	// shorturlDescLongURL is the schema descriptor for long_url field.
	shorturlDescLongURL := shorturlFields[2].Descriptor()
	// shorturl.LongURLValidator is a validator for the "long_url" field. It is called by the builders before save.
	shorturl.LongURLValidator = func() func(string) error {
		validators := shorturlDescLongURL.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(long_url string) error {
			for _, fn := range fns {
				if err := fn(long_url); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// shorturlDescCreatedAt is the schema descriptor for created_at field.
	shorturlDescCreatedAt := shorturlFields[3].Descriptor()
	// shorturl.DefaultCreatedAt holds the default value on creation for the created_at field.
	shorturl.DefaultCreatedAt = shorturlDescCreatedAt.Default.(func() time.Time)
	// shorturlDescIsDeleted is the schema descriptor for is_deleted field.
	shorturlDescIsDeleted := shorturlFields[5].Descriptor()
	// shorturl.DefaultIsDeleted holds the default value on creation for the is_deleted field.
	shorturl.DefaultIsDeleted = shorturlDescIsDeleted.Default.(bool)
	// shorturlDescAccessCount is the schema descriptor for access_count field.
	shorturlDescAccessCount := shorturlFields[6].Descriptor()
	// shorturl.DefaultAccessCount holds the default value on creation for the access_count field.
	shorturl.DefaultAccessCount = shorturlDescAccessCount.Default.(int)
	// shorturlDescCreatorIP is the schema descriptor for creator_ip field.
	shorturlDescCreatorIP := shorturlFields[7].Descriptor()
	// shorturl.CreatorIPValidator is a validator for the "creator_ip" field. It is called by the builders before save.
	shorturl.CreatorIPValidator = shorturlDescCreatorIP.Validators[0].(func(string) error)
	// shorturlDescCreatorID is the schema descriptor for creator_id field.
	shorturlDescCreatorID := shorturlFields[8].Descriptor()
	// shorturl.CreatorIDValidator is a validator for the "creator_id" field. It is called by the builders before save.
	shorturl.CreatorIDValidator = shorturlDescCreatorID.Validators[0].(func(string) error)
}
