// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend-shorturl/internal/data/ent/predicate"
	"backend-shorturl/internal/data/ent/shorturl"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShorturlDelete is the builder for deleting a Shorturl entity.
type ShorturlDelete struct {
	config
	hooks    []Hook
	mutation *ShorturlMutation
}

// Where appends a list predicates to the ShorturlDelete builder.
func (sd *ShorturlDelete) Where(ps ...predicate.Shorturl) *ShorturlDelete {
	sd.mutation.Where(ps...)
	return sd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sd *ShorturlDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, sd.sqlExec, sd.mutation, sd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sd *ShorturlDelete) ExecX(ctx context.Context) int {
	n, err := sd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sd *ShorturlDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(shorturl.Table, sqlgraph.NewFieldSpec(shorturl.FieldID, field.TypeInt64))
	if ps := sd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sd.mutation.done = true
	return affected, err
}

// ShorturlDeleteOne is the builder for deleting a single Shorturl entity.
type ShorturlDeleteOne struct {
	sd *ShorturlDelete
}

// Where appends a list predicates to the ShorturlDelete builder.
func (sdo *ShorturlDeleteOne) Where(ps ...predicate.Shorturl) *ShorturlDeleteOne {
	sdo.sd.mutation.Where(ps...)
	return sdo
}

// Exec executes the deletion query.
func (sdo *ShorturlDeleteOne) Exec(ctx context.Context) error {
	n, err := sdo.sd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{shorturl.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sdo *ShorturlDeleteOne) ExecX(ctx context.Context) {
	if err := sdo.Exec(ctx); err != nil {
		panic(err)
	}
}
