// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ShorturlsColumns holds the columns for the "shorturls" table.
	ShorturlsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "short_code", Type: field.TypeString, Unique: true, Size: 20},
		{Name: "long_url", Type: field.TypeString, Size: 2048, SchemaType: map[string]string{"mysql": "varchar(2048) COLLATE utf8mb4_bin"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "expire_at", Type: field.TypeTime, Nullable: true},
		{Name: "is_deleted", Type: field.TypeBool, Default: false},
		{Name: "access_count", Type: field.TypeInt, Default: 0},
		{Name: "creator_ip", Type: field.TypeString, Nullable: true, Size: 45},
		{Name: "creator_id", Type: field.TypeString, Nullable: true, Size: 64},
	}
	// ShorturlsTable holds the schema information for the "shorturls" table.
	ShorturlsTable = &schema.Table{
		Name:       "shorturls",
		Columns:    ShorturlsColumns,
		PrimaryKey: []*schema.Column{ShorturlsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ShorturlsTable,
	}
)

func init() {
	ShorturlsTable.Annotation = &entsql.Annotation{
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
		Options:   "COMMENT='短链映射表'",
	}
}
